### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by Ornolfr** [mirrajabi/ViewEffects#3]
```
java.lang.IllegalArgumentException: x must be >= 0
                                                                               at android.graphics.Bitmap.checkXYSign(Bitmap.java:364)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:639)
                                                                               at ir.mirrajabi.viewfilter.core.ViewFilter.getFilteredBackgroundOfView(ViewFilter.java:50)
                                                                               at ir.mirrajabi.viewfilter.core.ViewFilter$1.run(ViewFilter.java:39)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5281)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

```

**Comment by mirrajabi** [comment]
@Ornolfr
Thanks for the feedback.
I know this one. It happens when the view is not drawn yet but we are trying to use some of its logic that is dependent to layout size.
I don't have a solution yet. If anyone has I will gladly add an update to fix it.

For now if you have this issue just try putting your code inside `onPostCreate` or some elsewhere that you know happens after the activity is fully created and drawn.
